#!/usr/bin/env python3
import serial
import time
import json
import sys
from io import StringIO

maxSpeed = 1400;
stopSpeed = 1500;

def calcSpeed(distance, isFront): #1 for front and 0 for left
    
    speed = stopSpeed - (distance - 50)/220 *(100)
    if (speed < 1400):
        speed = 1400
    elif (speed >1500) :
        speed = 1500
        
    print (distance, " ", speed)
    return 1600

if __name__ == '__main__':
    ser = serial.Serial('/dev/ttyUSB1', 9600, timeout=1)
    ser.flush()
    front =0;
    back = 0;
    out = json.dumps({"speed": 1500}) + "\n"
    ser.write(out.encode())
    while True:
        print ("inside while loop")
        out = json.dumps({"speed": calcSpeed(front, 1)}) + "\n"
        ser.write(out.encode())
        line = ser.readline().decode('utf-8').rstrip().replace('\'', '\"').replace('\n','')
        #line = eval(line)
        if (line == ''): continue
        
        sensorInput = json.loads(line)
    
        front = sensorInput["frontDistance"]
        back = sensorInput["backDistance"]
        
        print("front: " + str(front) + ", back: " + str(back))
        #time.sleep(1)
        #out = json.dumps({"speed": calcSpeed(front, 1)}) + "\n"
        #ser.write(out.encode())
        
        